ntfy:
  server: https://ntfy.sh
  topic: iranwar-notifiert
  default_priority: 3
  # icon: https://example.com/your-icon.png
notify_on_first_run: false
keywords:
- iran
- war
- breaking
- pattern: executive\s+order
  regex: true
logging:
  level: INFO
web:
  enabled: true
  port: 8550
channels:
- name: Reddit worldnews
  type: reddit
  subreddits:
  - worldnews
  - wallstreetbetsGER
  sort: new
  poll_interval: 600
- name: BBC News
  type: rss
  feeds:
  - http://feeds.bbci.co.uk/news/world/rss.xml
  poll_interval: 900
  keywords:
  - iran
  - war
  - sanctions
